name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Next Version"
        required: true
        default: "x.y.z"
      release_note:
        description: "Release Note"
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create Tag
        run: |
          git tag v${{ github.event.inputs.version }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ github.event.inputs.release_note }}
