name: release

on:
  workflow_dispatch:
    inputs:
      update_type:
        description: "Update Type"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch
      release_note:
        description: "Release Note"
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get New Version
        id: get_new_version
        run: |
          # Get Current Version (ex. 0.3.6)
          CurrentVersion=`git describe --tags --abbrev=0 | cut -c 2-`
          echo $CurrentVersion
          # Divide Version with Space (ex. 0 3 6)
          SpaceDividedVersion=${CurrentVersion//./ }
          # Make Array (ex. (0 3 6))
          VersionArray=()
          for i in $SpaceDividedVersion; do VersionArray+=($i) ; done
          # Insert the Versions into Variable
          MajorVersion=${VersionArray[0]}
          MinorVersion=${VersionArray[1]}
          PatchVersion=${VersionArray[2]}
          # Update to New Version
          if [ ${UPDATE_TYPE} = "major" ]; then MajorVersion=$((MajorVersion + 1))
          elif [ ${UPDATE_TYPE} = "minor" ]; then MinorVersion=$((MinorVersion + 1))
          else PatchVersion=$((PatchVersion + 1)); fi
          # Output New Version
          echo $MajorVersion
          echo $MinorVersion
          echo $PatchVersion
          echo $MajorVersion.$MinorVersion.$PatchVersion
          echo "new_version=$MajorVersion.$MinorVersion.$PatchVersion" >> $GITHUB_OUTPUT
        env:
          UPDATE_TYPE: ${{ github.event.inputs.update_type }}
      - name: Create Tag
        run: |
          git tag v${{ steps.get_new_version.outputs.new_version }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          body: ${{ github.event.inputs.release_note }}
          tag: v${{ steps.get_new_version.outputs.new_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
